/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import BaseDatos.Conexion;
import Calculos.*;
import XMLL.archivoXML;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import sun.util.calendar.BaseCalendar.Date;

/**
 *
 * @author Yosse
 */
public class FrmInterfaz1 extends javax.swing.JFrame {

    /**
     * Creates new form FrmInterfaz1
     */
    private String url;
    String nombree;
    Calculos mCalculos = new Calculos();
    String rfcr;
    double impuesto;
    int entradafac;
    double Ganancia;
    double Perdida;
    float result;
    float Sueldo;
    float Ganacias;
    String Fecha;
    String mes;
    String anyo;
    Calendar Calendario = Calendar.getInstance();
    ImageIcon icono = new javax.swing.ImageIcon(getClass().getResource(""));

    public FrmInterfaz1() {
        initComponents();
        url = "";
        impuesto = 0;
        LblTipo.setText("Nose~Soft");
        rfcr = "";
        entradafac = 0;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PestanaLeerarchivo = new javax.swing.JPanel();
        BtnCargar = new javax.swing.JButton();
        TxtRFC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BtnSalir1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pestanaconsulta = new javax.swing.JPanel();
        LblTipo = new javax.swing.JLabel();
        Lbl3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblNombree = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Lbl4 = new javax.swing.JLabel();
        LblRFCR = new javax.swing.JLabel();
        Lbl2 = new javax.swing.JLabel();
        LblNombrer = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        LblRFCE = new javax.swing.JLabel();
        BtnSalir = new javax.swing.JButton();
        pestanaGenerarreporte = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbxMes = new javax.swing.JComboBox();
        cmbxTipoDeReporte1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TXTanyo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Lblimpuesto = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Lblganancias = new javax.swing.JLabel();
        LblPerdidas = new javax.swing.JLabel();
        TXTSueldo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtdir = new javax.swing.JLabel();
        BtnSALIR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 204));

        PestanaLeerarchivo.setBackground(new java.awt.Color(204, 204, 255));

        BtnCargar.setText("Cargar Archivo");
        BtnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCargarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Adobe Arabic", 0, 24)); // NOI18N
        jLabel2.setText("Introduzca RFC:");

        BtnSalir1.setText("Salir");
        BtnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PestanaLeerarchivoLayout = new javax.swing.GroupLayout(PestanaLeerarchivo);
        PestanaLeerarchivo.setLayout(PestanaLeerarchivoLayout);
        PestanaLeerarchivoLayout.setHorizontalGroup(
            PestanaLeerarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestanaLeerarchivoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PestanaLeerarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PestanaLeerarchivoLayout.createSequentialGroup()
                        .addGroup(PestanaLeerarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PestanaLeerarchivoLayout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(BtnCargar))
                            .addGroup(PestanaLeerarchivoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(461, Short.MAX_VALUE))
                    .addGroup(PestanaLeerarchivoLayout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        PestanaLeerarchivoLayout.setVerticalGroup(
            PestanaLeerarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestanaLeerarchivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PestanaLeerarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(BtnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PestanaLeerarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PestanaLeerarchivoLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(BtnSalir1)
                        .addContainerGap(138, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PestanaLeerarchivoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
        );

        jTabbedPane1.addTab("Leer Archivo", PestanaLeerarchivo);

        LblTipo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        LblTipo.setText("___________");

        Lbl3.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        Lbl3.setText("Nombre Emisor:");

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel3.setText("RFC EMISOR:");

        LblNombree.setText("___________________________");

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        jLabel4.setText("RFC RECEPTOR:");

        Lbl4.setFont(new java.awt.Font("Book Antiqua", 0, 14)); // NOI18N
        Lbl4.setText("Nombre Receptor:");

        LblRFCR.setText("___________________________");

        Lbl2.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        Lbl2.setText("Fecha:");

        LblNombrer.setText("___________________________");

        LblFecha.setText("_______________________");

        LblRFCE.setText("___________________________");

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pestanaconsultaLayout = new javax.swing.GroupLayout(pestanaconsulta);
        pestanaconsulta.setLayout(pestanaconsultaLayout);
        pestanaconsultaLayout.setHorizontalGroup(
            pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestanaconsultaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(pestanaconsultaLayout.createSequentialGroup()
                .addGroup(pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestanaconsultaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pestanaconsultaLayout.createSequentialGroup()
                                .addComponent(Lbl3)
                                .addGap(49, 49, 49)
                                .addComponent(LblNombree))
                            .addGroup(pestanaconsultaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(LblRFCE, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)
                        .addGroup(pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pestanaconsultaLayout.createSequentialGroup()
                                .addComponent(Lbl4)
                                .addGap(28, 28, 28)
                                .addComponent(LblNombrer))
                            .addGroup(pestanaconsultaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, 0)
                                .addComponent(LblRFCR, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pestanaconsultaLayout.createSequentialGroup()
                        .addComponent(LblTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(Lbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        pestanaconsultaLayout.setVerticalGroup(
            pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestanaconsultaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pestanaconsultaLayout.createSequentialGroup()
                        .addComponent(LblTipo)
                        .addGap(146, 146, 146))
                    .addGroup(pestanaconsultaLayout.createSequentialGroup()
                        .addGroup(pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl2)
                            .addComponent(LblFecha))
                        .addGap(18, 18, 18)
                        .addGroup(pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(LblRFCR, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(LblRFCE, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pestanaconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lbl4)
                            .addComponent(LblNombrer)
                            .addComponent(Lbl3)
                            .addComponent(LblNombree))
                        .addGap(48, 48, 48)))
                .addGap(20, 20, 20)
                .addComponent(BtnSalir)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta Del Archivo", pestanaconsulta);

        jButton1.setText("Generar Reporte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Elige El Tipo De Reporte");

        cmbxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        cmbxTipoDeReporte1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reporte Mensual" }));

        jLabel6.setText("Elige El Mes");

        jLabel7.setText("Ingresa el año");

        TXTanyo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTanyoKeyTyped(evt);
            }
        });

        jLabel8.setText("IMPUESTOS");

        jLabel9.setText("GANANCIAS");

        Lblimpuesto.setText("____________");

        jLabel12.setText("PERDIDAS");

        Lblganancias.setText("____________");

        LblPerdidas.setText("____________");

        TXTSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTSueldoKeyTyped(evt);
            }
        });

        jLabel10.setText("Ingresa El Sueldo Mensual");

        BtnSALIR.setText("Salir");
        BtnSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pestanaGenerarreporteLayout = new javax.swing.GroupLayout(pestanaGenerarreporte);
        pestanaGenerarreporte.setLayout(pestanaGenerarreporteLayout);
        pestanaGenerarreporteLayout.setHorizontalGroup(
            pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(Lblimpuesto))
                            .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(jButton1)
                                .addGap(57, 57, 57)
                                .addComponent(jtxtdir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                                .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(LblPerdidas)
                                            .addComponent(Lblganancias))))
                                .addGap(220, 220, 220)
                                .addComponent(BtnSALIR))))
                    .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbxTipoDeReporte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(TXTSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                                .addComponent(TXTanyo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(jLabel6)
                                .addGap(29, 29, 29)
                                .addComponent(cmbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        pestanaGenerarreporteLayout.setVerticalGroup(
            pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxTipoDeReporte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXTanyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtdir, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(56, 56, 56)
                .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Lblimpuesto))
                .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestanaGenerarreporteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Lblganancias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pestanaGenerarreporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(LblPerdidas))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestanaGenerarreporteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSALIR)
                        .addGap(78, 78, 78))))
        );

        jTabbedPane1.addTab("Generar Reporte", pestanaGenerarreporte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 898, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_BtnSalirActionPerformed
    private void Cargar() {

        try {
            //int opa;
            //do {
            JFileChooser dato = new JFileChooser();
            int op = dato.showOpenDialog(this);

            if (op == JFileChooser.APPROVE_OPTION) {

                url = dato.getSelectedFile().getPath();
            }

            if (url == "") {

                JOptionPane.showMessageDialog(null, "No Seleccionaste Nada");
            } else {

                archivoXML mi_archivo = new archivoXML(url);
                mi_archivo.open();
                try {
                    Vector vector_resultado = new Vector();
                    NodeList root = mi_archivo.getRoot();
                    //Padre
                    Node comprobante = mi_archivo.getNode("cfdi:Comprobante", root);
                    String folio = mi_archivo.getNodeAttr("folio", comprobante);
                    String importe = mi_archivo.getNodeAttr("subTotal", comprobante);
                    String fecha = mi_archivo.getNodeAttr("fecha", comprobante);
                    System.out.println(folio);
                    System.out.println(importe);
                    System.out.println(fecha);
                    //Emisor
                    Node emisor = mi_archivo.getNode("cfdi:Emisor", comprobante.getChildNodes());
                    String rfce = mi_archivo.getNodeAttr("rfc", emisor);
                    nombree = mi_archivo.getNodeAttr("nombre", emisor);
                    System.out.println(rfce);
                    System.out.println(nombree);
                    //Receptor
                    Node receptor = mi_archivo.getNode("cfdi:Receptor", comprobante.getChildNodes());
                    rfcr = mi_archivo.getNodeAttr("rfc", receptor);
                    String nombrer = mi_archivo.getNodeAttr("nombre", receptor);
                    System.out.println(rfcr);
                    System.out.println(nombrer);
                    //Traslados
                    Node Traslados = mi_archivo.getNode("cfdi:Impuestos", comprobante.getChildNodes());
                    String traslados = mi_archivo.getNodeAttr("totalImpuestosTrasladados", Traslados);
                    String retenciones = mi_archivo.getNodeAttr("totalImpuestosRetenidos", Traslados);
                    System.out.println(traslados);
                    System.out.println(retenciones);

                    /*LblNombree.setText(nombree);
                     LblFecha.setText(fecha);
                     //LblImpuestos.setText(String.valueOf("Aqui Se Mostrará Su Determinado Valor"));
                 ty    LblNombrer.setText(nombrer);
                     LblRFCR.setText(rfcr);
                     this.LblRFCE.setText(rfce);*/

                    /* //Esto es para insertar osease guardar en la base los datos
                     try {
                     //Conectamos con la base de datos
                     Conexion mConexion = new Conexion();
                     mConexion.Conectar("localhost", "nose_prueba", "root", "nose");
                     //Formamos una instruccion DML -INSERT
                     String INSERT = "insert into recibo_factura values ('?1','?2','?3','?4','?5','?6','?7','?8')";
                     INSERT = INSERT.replace("?1", folio);
                     INSERT = INSERT.replace("?2", importe);
                     INSERT = INSERT.replace("?3", fecha);
                     INSERT = INSERT.replace("?4", nombrer);
                     INSERT = INSERT.replace("?5", nombree);
                     INSERT = INSERT.replace("?6", rfcr);
                     INSERT = INSERT.replace("?7", rfce);
                     INSERT = INSERT.replace("?8", "1");
                     //Llamamos al metodo que se encuentra en la clase conexión en el packete BaseDatos
                     mConexion.ejecutarActualizacion(INSERT);
                     JOptionPane.showMessageDialog(this, "guardado");
                     this.setVisible(false);

                     } catch (Exception error) {
                     JOptionPane.showMessageDialog(this, "Error de guardar en la base de datos");
                     System.out.println(error.toString());
                     }*/
                    System.out.println(TxtRFC.getText());
                    if (TxtRFC.getText().equals(rfce.toString())) {
                        //Recibo
                        LblNombree.setText(nombree);
                        LblFecha.setText(fecha);
                        LblTipo.setText("Recibo");
                        LblRFCE.setText(rfce);
                        impuesto = mCalculos.CalcularImpuestosRecibo(Float.parseFloat(importe));
                        //LblImpuestos.setText(String.valueOf("impuesto"));
                        try {
                            //Conectamos con la base de datos
                            Conexion mConexion = new Conexion();
                            mConexion.Conectar("localhost", "nose_prueba", "root", "nose");
                            //Formamos una instruccion DML -INSERT
                            String INSERT = "insert into recibo_factura values ('?1','?2','?3','?4','?5','?6','?7','?8','?9')";
                            INSERT = INSERT.replace("?1", folio);
                            INSERT = INSERT.replace("?2", importe);
                            INSERT = INSERT.replace("?3", fecha);
                            INSERT = INSERT.replace("?4", nombrer);
                            INSERT = INSERT.replace("?5", nombree);
                            INSERT = INSERT.replace("?6", rfcr);
                            INSERT = INSERT.replace("?7", rfce);
                            INSERT = INSERT.replace("?8", "1");
                            //Llamamos al metodo que se encuentra en la clase conexión en el packete BaseDatos
                            INSERT = INSERT.replace("?9", String.valueOf(impuesto));
                            mConexion.ejecutarActualizacion(INSERT);
                            JOptionPane.showMessageDialog(this, "guardado");
                            //this.setVisible(false);
                        } catch (Exception error) {
                            JOptionPane.showMessageDialog(this, "Error de guardar en la base de datos");
                            System.out.println(error.toString());
                        }

                    } else if (TxtRFC.getText().equals(rfcr.toString())) {
                        //Factura
                        LblNombrer.setText(nombrer);
                        LblTipo.setText("Factura");
                        LblRFCR.setText(rfcr);
                        impuesto = mCalculos.CalcularImpuestosFactura(Float.parseFloat(importe));
                        //this.LblImpuestos.setText(String.valueOf(impuesto));

                        try {
                            //Conectamos con la base de datos
                            Conexion mConexion = new Conexion();
                            mConexion.Conectar("localhost", "nose_prueba", "root", "nose");
                            //Formamos una instruccion DML -INSERT
                            String INSERT = "insert into recibo_factura values ('?1','?2','?3','?4','?5','?6','?7','?8','?9')";
                            INSERT = INSERT.replace("?1", folio);
                            INSERT = INSERT.replace("?2", importe);
                            INSERT = INSERT.replace("?3", fecha);
                            INSERT = INSERT.replace("?4", nombrer);
                            INSERT = INSERT.replace("?5", nombree);
                            INSERT = INSERT.replace("?6", rfcr);
                            INSERT = INSERT.replace("?7", rfce);
                            //munero 2 para identiificar el tipo en la base de datos como una factura
                            INSERT = INSERT.replace("?8", "2");
                            INSERT = INSERT.replace("?9", String.valueOf(impuesto));
                            //Llamamos al metodo que se encuentra en la clase conexión en el packete BaseDatos
                            mConexion.ejecutarActualizacion(INSERT);
                            JOptionPane.showMessageDialog(this, "guardado");
                            //this.setVisible(false);
                        } catch (Exception error) {
                            JOptionPane.showMessageDialog(this, "Error de guardar en la base de datos");
                            System.out.println(error.toString());
                        }
                    } else {

                        JOptionPane.showMessageDialog(null, "RFC NO ENCONTRADO");

                    }

                } catch (Exception error) {
                    JOptionPane.showMessageDialog(null, "Error No Puedes abrir ese archivo");
                }
                if (rfcr.toString() == "") {
                    JOptionPane.showMessageDialog(null, "ESTE NO ES UN ARCHIVO FACTURA NI RECIBO");

                }
            }
                //opa = JOptionPane.showConfirmDialog(rootPane, "Desea Cargar Otro Archivo?");

            // } while ((opa != 1) && (opa != 2));
        } catch (Exception error) {
            JOptionPane.showMessageDialog(null, "Error No Puedes abrir ese archivo");
            //System.out.print(error.toString());
        }

    }
    private void BtnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCargarActionPerformed

        // TODO add your handling code here:
        if (this.TxtRFC.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe Introducir su RFC");
        } else {

            if (entradafac == 0) {
                Cargar();
            } else if (entradafac > 0) {
                int a = JOptionPane.showConfirmDialog(rootPane, "Seguro que quieres cargar otra factura o recibo?");
                if (a == 0) {
                    Cargar();
                }

            }
            entradafac = 1;
        }
    }//GEN-LAST:event_BtnCargarActionPerformed

    private void BtnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSalir1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String d = jtxtdir.getText();
        mes = (String) this.cmbxMes.getSelectedItem();

        //this.jPanel1.add(imagen);
        //this.jPanel1.repaint();
        if (mes == "Enero") {
            mes = String.valueOf("01");
        } else if (mes == "Febrero") {
            mes = String.valueOf("02");
        } else if (mes == "Marzo") {
            mes = String.valueOf("03");
        } else if (mes == "Abril") {
            mes = String.valueOf("04");
        } else if (mes == "Mayo") {
            mes = String.valueOf("05");
        } else if (mes == "Junio") {
            mes = String.valueOf("06");
        } else if (mes == "Julio") {
            mes = String.valueOf("07");
        } else if (mes == "Agosto") {
            mes = String.valueOf("08");
        } else if (mes == "Septiembre") {
            mes = String.valueOf("09");
        } else if (mes == "Octubre") {
            mes = String.valueOf("10");
        } else if (mes == "Noviembre") {
            mes = String.valueOf("11");
        } else if (mes == "Diciembre") {
            mes = String.valueOf("12");
        }

        if ((this.TXTSueldo.getText().equals("")) || (this.TXTanyo.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Campos Vacios verifica tu información");
        } else if (((Integer.parseInt(this.TXTanyo.getText())) > Calendario.getWeekYear()) && ((Integer.parseInt(mes) > Calendario.get(Calendar.MONTH)))) {
            JOptionPane.showMessageDialog(null, "Verifica tu fecha");
        } else if (((Integer.parseInt(this.TXTanyo.getText())) == Calendario.getWeekYear()) && ((Integer.parseInt(mes) > Calendario.get(Calendar.MONTH)))) {
            JOptionPane.showMessageDialog(null, " Upss Verifica tu mes");
        } else if (((Integer.parseInt(this.TXTanyo.getText())) < Calendario.getWeekYear())) {

            System.out.println(mes);
            anyo = this.TXTanyo.getText();
            mCalculos = new Calculos();
            result = mCalculos.ImpuestosMensuales(mes, anyo);
            if (result == 0) {
                JOptionPane.showMessageDialog(null, "no existen facturas ni recibos en esta fecha");
            } else {

                this.Lblimpuesto.setText(String.valueOf(result));
                Sueldo = Float.parseFloat(this.TXTSueldo.getText());
                Ganacias = mCalculos.CalcularGananciasPerdidasMensuales(Sueldo);
                if (Ganacias > 0) {
                    this.Lblganancias.setText(String.valueOf(Ganacias));
                    this.LblPerdidas.setText("0");
                    this.Ganancia = Ganacias;
                    this.Perdida = 0;

                } else if (Ganacias < 0) {
                    this.Lblganancias.setText("0");
                    this.LblPerdidas.setText(String.valueOf(Ganacias));
                    this.Perdida = Ganacias;
                    this.Ganacias = 0;

                }
                System.out.println(result);
                Fecha = anyo + "-" + mes + "-" + "01";
                System.out.println(Fecha);
                System.out.println(Ganacias);
                System.out.println(Perdida);

                try {
                    //Conectamos con la base de datos

                    Conexion mConexion = new Conexion();
                    mConexion.Conectar("localhost", "nose_prueba", "root", "nose");
                    //Formamos una instruccion DML -INSERT
                    String INSERT = "insert into resultados values (?1,'?2','?3','?4','?5','?6')";
                    INSERT = INSERT.replace("?1", String.valueOf("null"));
                    INSERT = INSERT.replace("?2", String.valueOf(result));
                    INSERT = INSERT.replace("?3", String.valueOf(Ganacias));
                    INSERT = INSERT.replace("?4", String.valueOf(Perdida));
                    INSERT = INSERT.replace("?5", "0");
                    INSERT = INSERT.replace("?6", Fecha);
                    System.out.println(INSERT);
                    //Llamamos al metodo que se encuentra en la clase conexión en el packete BaseDatos
                    mConexion.ejecutarActualizacion(INSERT);
                    JOptionPane.showMessageDialog(this, "guardado");
//            this.setVisible(false);

                } catch (Exception error) {
                    JOptionPane.showMessageDialog(this, "Error de guardar en la base de datos puede ser que ya se aya guardado en la base de datos");
                    System.out.println(error.toString());
                }
                // String a=this.jtxtcont.getText();
                try {
                    JOptionPane.showMessageDialog(this, "Selecciona La Ruta En Donde Se Guardará El Reporte");

                    JFileChooser dlg = new JFileChooser();
                    int option = dlg.showSaveDialog(this);
                    Image imagen = Image.getInstance("C:\\Users\\Acer\\Documents\\Septimo Semestre\\Nacho-Scrum\\Pruebas_Nose\\PruebasN\\Nose\\src\\IMG-20171104-WA0004.jpg");
                    imagen.scaleAbsoluteWidth(20f);

                    if (option == JFileChooser.APPROVE_OPTION) {

                        File f = dlg.getSelectedFile();
                        String f1 = f.toString();
                        this.jtxtdir.setText(f1);
                    }
                    String a = "Reporte del mes de " + this.cmbxMes.getSelectedItem().toString() + " " + this.TXTanyo.getText() + "\n\n" + "Impuestos mensuales: " + this.Lblimpuesto.getText() + "\n Ganancias Mensuales: " + this.Lblganancias.getText() + "\n Pedidas Mensuales: " + this.LblPerdidas.getText();
                    FileOutputStream archivo = new FileOutputStream(d + ".pdf");
                    Document doc = new Document();
                    PdfWriter.getInstance(doc, archivo);
                    doc.open();
                    Font mFont = new Font();
                    doc.add(new Paragraph(a));
                    doc.add(imagen);
                    doc.close();
                    //JOptionPane.showMessageDialog(null, "Documento creado con exito");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "error" + e);
                }
            }

        } else if (((Integer.parseInt(this.TXTanyo.getText())) == Calendario.getWeekYear()) && ((Integer.parseInt(mes) <= Calendario.get(Calendar.MONTH)))) {

            System.out.println(mes);
            anyo = this.TXTanyo.getText();
            mCalculos = new Calculos();
            result = mCalculos.ImpuestosMensuales(mes, anyo);
            if (result == 0) {
                JOptionPane.showMessageDialog(null, "No existen facturas ni recibos en esta fecha");
            } else {

                this.Lblimpuesto.setText(String.valueOf(result));
                Sueldo = Float.parseFloat(this.TXTSueldo.getText());
                Ganacias = mCalculos.CalcularGananciasPerdidasMensuales(Sueldo);
                if (Ganacias > 0) {
                    this.Lblganancias.setText(String.valueOf(Ganacias));
                    this.LblPerdidas.setText("0");
                    this.Ganancia = Ganacias;
                    this.Perdida = 0;

                } else if (Ganacias < 0) {
                    this.Lblganancias.setText("0");
                    this.LblPerdidas.setText(String.valueOf(Ganacias));
                    this.Perdida = Ganacias;
                    this.Ganacias = 0;

                }
                System.out.println(result);
                Fecha = anyo + "-" + mes + "-" + "01";
                System.out.println(Fecha);
                System.out.println(Ganacias);
                System.out.println(Perdida);

                try {
                    //Conectamos con la base de datos

                    Conexion mConexion = new Conexion();
                    mConexion.Conectar("localhost", "nose_prueba", "root", "nose");
                    //Formamos una instruccion DML -INSERT
                    String INSERT = "insert into resultados values (?1,'?2','?3','?4','?5','?6')";
                    INSERT = INSERT.replace("?1", String.valueOf("null"));
                    INSERT = INSERT.replace("?2", String.valueOf(result));
                    INSERT = INSERT.replace("?3", String.valueOf(Ganacias));
                    INSERT = INSERT.replace("?4", String.valueOf(Perdida));
                    INSERT = INSERT.replace("?5", "0");
                    INSERT = INSERT.replace("?6", Fecha);
                    System.out.println(INSERT);
                    //Llamamos al metodo que se encuentra en la clase conexión en el packete BaseDatos
                    mConexion.ejecutarActualizacion(INSERT);
                    JOptionPane.showMessageDialog(this, "guardado");
//            this.setVisible(false);

                } catch (Exception error) {
                    JOptionPane.showMessageDialog(this, "No Se Guardo En La BD Pues Ya Esta Guardado");
                    System.out.println(error.toString());
                }
                // String a=this.jtxtcont.getText();
                try {
                    JOptionPane.showMessageDialog(this, "Selecciona La Ruta En Donde Se Guardará El Reporte");

                    JFileChooser dlg = new JFileChooser();
                    int option = dlg.showSaveDialog(this);
                    Image imagen = Image.getInstance("C:\\Users\\Acer\\Documents\\Septimo Semestre\\Nacho-Scrum\\Pruebas_Nose\\PruebasN\\Nose\\src\\IMG-20171104-WA0004.jpg");
//            imagen.setAbsolutePosition(50f, 50f);
                    imagen.scalePercent(30f);
                    imagen.setAlignment(Element.ALIGN_RIGHT);

                    if (option == JFileChooser.APPROVE_OPTION) {

                        File f = dlg.getSelectedFile();
                        String f1 = f.toString();
                        this.jtxtdir.setText(f1);
                    }
                    String a = "Reporte del mes de " + this.cmbxMes.getSelectedItem().toString() + " " + this.TXTanyo.getText() + "\n" + "Impuestos mensuales: " + this.Lblimpuesto.getText() + "\n Ganancias Mensuales: " + this.Lblganancias.getText() + "\n Pedidas Mensuales: " + this.LblPerdidas.getText();
                    FileOutputStream archivo = new FileOutputStream(d + ".pdf");
                    Document doc = new Document();
                    PdfWriter.getInstance(doc, archivo);
                    doc.open();
                    Font mFont = new Font();
                    doc.add(imagen);
                    doc.add(new Paragraph(a));
                    doc.close();
                    //   JOptionPane.showMessageDialog(null, "Documento creado con exito");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "error" + e);
                }

            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void TXTSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTSueldoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE) && (caracter != '.')) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_TXTSueldoKeyTyped

    private void TXTanyoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTanyoKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo numeros");
        }
    }//GEN-LAST:event_TXTanyoKeyTyped

    private void BtnSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSALIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnSALIRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInterfaz1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInterfaz1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInterfaz1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInterfaz1.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInterfaz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCargar;
    private javax.swing.JButton BtnSALIR;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSalir1;
    private javax.swing.JLabel Lbl2;
    private javax.swing.JLabel Lbl3;
    private javax.swing.JLabel Lbl4;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JLabel LblNombree;
    private javax.swing.JLabel LblNombrer;
    private javax.swing.JLabel LblPerdidas;
    private javax.swing.JLabel LblRFCE;
    private javax.swing.JLabel LblRFCR;
    private javax.swing.JLabel LblTipo;
    private javax.swing.JLabel Lblganancias;
    private javax.swing.JLabel Lblimpuesto;
    private javax.swing.JPanel PestanaLeerarchivo;
    private javax.swing.JTextField TXTSueldo;
    private javax.swing.JTextField TXTanyo;
    private javax.swing.JTextField TxtRFC;
    private javax.swing.JComboBox cmbxMes;
    private javax.swing.JComboBox cmbxTipoDeReporte1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jtxtdir;
    private javax.swing.JPanel pestanaGenerarreporte;
    private javax.swing.JPanel pestanaconsulta;
    // End of variables declaration//GEN-END:variables
}
